monolog:
    handlers:
        # Console log for "docker logs" command
        stderr:
            type:  stream
            path:  'php://stderr'
            level: notice
        # Log file with more detailed info
        file:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            max_files: 10
        # Disable default "stdout" handler
        stdout:
            type: 'null'
