monolog:
    handlers:
        stdout:
            type:  stream
            path:  "php://stdout"
            level: debug
        stderr:
            type:  stream
            path:  "php://stderr"
            level: notice
        console:
            type:  console
            level: debug