monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            level: debug